MAP = [
       [list("RRRRRRRR"),
        list("RRYYBBG/"), 
        list("B.....YY"),
        list("......Y/"),
        list("........"),
        list("......./"),
        list("........"),
        list("......./"),
        list("........"), 
        list("......./"),
        list("........")],
       
        [list("RRYYBBGG"),
        list("RRYYBBG/"), 
        list("BBGGRRYY"),
        list("BGGRRYY/"),
        list("........"),
        list("......./"),
        list("........"),
        list("......./"),
        list("........"), 
        list("......./"),
        list("........")],
       
       [list("RRRRRRGG"),
        list("RRYYBBG/"), 
        list("BBGGRRYY"),
        list("BGGRRYY/"),
        list("........"),
        list("......./"),
        list("........"),
        list("......./"),
        list("........"), 
        list("......./"),
        list("........")]]